server:
  port: 8001
  servlet:
    contextPath: "/api/pull-up/"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: pull-up
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://54.180.202.16:3306/pullup?serverTimezone=Asia/Seoul
    username: root
    password: 1077
    hikari:
      maximum-pool-size: 10
  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
        format_sql: true


  # social security
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f9165f4a6bb04401b296313ef583fb98
            client-secret: wt0MHHY0Dp9vTTUYX4w7M8yEDZUSebcg
            redirect-uri: "http://localhost:8001/api/pull-up/oauth2/callback/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
            clientName: kakao
          apple:
            client-id: com.pull-up.apps
            client-secret: AuthKey_SNHA348FS6.p8/7MKFVNQYN5/SNHA348FS6
            redirect-uri: "http://localhost:8001/api/pull-up/oauth2/callback/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - name
              - email
            clientName: Apple
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            authorizationUri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            tokenUri: https://appleid.apple.com/auth/token
#            jwk-set-uri: https://appleid.apple.com/auth/keys
#            user-name-attribute: sub


#logging
logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    org:
      springframework:
        web: INFO
        apache:
          tiles: DEBUG
        springframework:
          boot: DEBUG
